---
common:
  - &install_dependencies_and_regen_data
    run:
      name: Install dependencies and regenerate reproducibility data.
      command: |
        virtualenv --python python3 .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        python3 check.py

version: 2
jobs:
  build37:
    docker:
      - image: circleci/python:buster
    steps:
      - checkout
      - *install_dependencies_and_regen_data
  build38:
    docker:
      - image: circleci/python:3.8.0-buster
    steps:
      - checkout
      - *install_dependencies_and_regen_data
  deploy:
    docker:
      - image: circleci/python:buster
    steps:
      - checkout
      - *install_dependencies_and_regen_data

workflows:
  version: 2
  jobs_per_pr:
    jobs:
      - build37
      - build38
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - deploy
