---
common:
  - &install_dependencies_and_regen_data
    run:
      name: Install dependencies and regenerate reproducibility data.
      command: |
        virtualenv --python python3 .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        python3 check.py
        cat site_data.json
      no_output_timeout: 20m

version: 2
jobs:
  build37:
    docker:
      - image: circleci/python:buster
    steps:
      - checkout
      - *install_dependencies_and_regen_data
  build38:
    docker:
      - image: circleci/python:3.8.0-buster
    steps:
      - checkout
      - *install_dependencies_and_regen_data
  deploy:
    docker:
      - image: circleci/python:buster
    steps:
      - checkout
      - *install_dependencies_and_regen_data
      - add_ssh_keys:
          fingerprints:
          - "76:dd:b7:82:dd:a2:ac:64:ec:38:ed:67:d7:91:6a:da"
      - run:
          name: commit changes and redeploy
          command: |
            git config user.email "jen+bot@freedom.press"
            git config user.name "redshiftzero-bot"
            git add docs/index.html
            git add site_data.json
            git commit -m "daily update"
            git push origin main

workflows:
  version: 2
  jobs_per_pr:
    jobs:
      - build37:
          filters:
            branches:
              ignore:
                - main
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - deploy
